apis/urls.py
from .views import messageAPI
from django.urls import path


app_name="apis"
urlpatterns = [
    path('message/', messageAPI, name="get-response"),
]

chatbot/urls.py
from chatbot.views import homeController
from django.urls import path


app_name="chatbot"
urlpatterns = [
    path('', homeController, name="home"),
]

django_chatbot/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("chatbot.urls",namespace="chatbot")),
    path('', include("apis.urls",namespace="apis")),


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apis/models.py
from django.db import models

# Create your models here.

chatbot/models.py
from django.db import models

# Create your models here.

apis/views.py
from django.shortcuts import render
from django.http import JsonResponse
import nltk
from nltk.stem import WordNetLemmatizer
import pickle
import numpy as np
from django.conf import settings
from keras.models import load_model
import json
import random


# Create your views here.
BASE_DIR = str(settings.BASE_DIR)+"/"
print(BASE_DIR)
lemmatizer = WordNetLemmatizer()

intents = json.loads(open(BASE_DIR + 'intents.json').read())
words = pickle.load(open(BASE_DIR + 'words.pkl','rb'))
classes = pickle.load(open(BASE_DIR + 'classes.pkl','rb'))
model = load_model(BASE_DIR + 'chatbot_model.h5')


def clean_up_sentence(sentence):
    # tokenize the pattern - split words into array
    sentence_words = nltk.word_tokenize(sentence)
    # stem each word - create short form for word
    sentence_words = [lemmatizer.lemmatize(word.lower()) for word in sentence_words]
    return sentence_words
# return bag of words array: 0 or 1 for each word in the bag that exists in the sentence

def getResponse(ints, intents_json):
    tag = ints[0]['intent']
    list_of_intents = intents_json['intents']
    for i in list_of_intents:
        if(i['tag']== tag):
            result = random.choice(i['responses'])
            break
    return result

def chatbot_response(text):
    ints = predict_class(text, model)
    res = getResponse(ints, intents)
    return res

def bow(sentence, words, show_details=True):
    # tokenize the pattern
    sentence_words = clean_up_sentence(sentence)
    # bag of words - matrix of N words, vocabulary matrix
    bag = [0]*len(words)
    for s in sentence_words:
        for i,w in enumerate(words):
            if w == s:
                # assign 1 if current word is in the vocabulary position
                bag[i] = 1
                if show_details:
                    print ("found in bag: %s" % w)
    return(np.array(bag))

def predict_class(sentence, model):
    # filter out predictions below a threshold
    p = bow(sentence, words,show_details=False)
    res = model.predict(np.array([p]))[0]
    ERROR_THRESHOLD = 0.25
    results = [[i,r] for i,r in enumerate(res) if r>ERROR_THRESHOLD]
    # sort by strength of probability
    results.sort(key=lambda x: x[1], reverse=True)
    return_list = []
    for r in results:
        return_list.append({"intent": classes[r[0]], "probability": str(r[1])})
    return return_list



    
        
        


def messageAPI(request):
    if request.method=="GET":
        message = request.GET.get("message")
        res = chatbot_response(message)
        
        return JsonResponse({"response":res})

chatbot/views.py
from django.shortcuts import render
from django.contrib.sites.shortcuts import get_current_site

# Create your views here.
def homeController(request):
    if request.method=="GET":
        domain = get_current_site(request).domain
        return render(request,"chatbot/home.html",{"domain":domain})

chatbot/templates/chatbot/home.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dr Foluke</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <style type="text/css">

    

        
        
        
        /* .chatsbox{
            flex: 1;
        } */
        
        .input{
            
            
            
            background-color: white;
            border-radius: 1000px;
            border:0px;
            padding: 10px 20px;
        }
        .send{
            background-color: blue;
            border: none;
            color: white;
            align-self: stretch;
            padding: 10px;
            border-radius: 500px;
        }
        .aichatbox{
            width: fit-content;
            margin-bottom: 30px;
        }
        .aichat{
            
            background-color: #fff;
            padding: 15px;
            border-radius: 1000px;
            min-width: 300px;
            margin-bottom: 10px;
        }
        .aichat__info{
            display: flex;
            align-items: center;
        }
        .aichat__image{
            width: 40px;
            height: 40px;
            object-fit: cover;
            border-radius: 1000px;
            margin-right: 10px;
        }
        .aichat__name{
            color: rgb(132, 136, 151);
        }
        .chatbox{
            width: fit-content;
            margin-left: auto;
            margin-bottom: 10px;
        }
        .chat{
            background-color: #fff;
            padding: 15px;
            border-radius: 1000px;
            min-width: 300px;
            margin-bottom: 10px;
        }
        .chat__info{
            display: flex;
            align-items: center;
            justify-content: flex-end;
        }
        .chat__image{
            width: 40px;
            height: 40px;
            object-fit: cover;
            border-radius: 1000px;
            margin-left: 10px;
        }
        .chat__name{
            color: rgb(132, 136, 151);
        }
    </style>
    
</head>

<body style="background-color: rgb(241, 242, 246);padding: 20px;">
<section>
    <div class="container">
        <div id="scrollable" class="chatsbox" style="overflow: auto;height: 90vh;">

            <div class="aichatbox">
                <div class="aichatmessages">
                    <div class="aichat">Hi my name is Dr Foluke</div>
                </div>
                <div class="aichat__info">
                    <img src="{% static 'sakura.jpg' %}" class="aichat__image" />
                    <span class="aichat__name">Dr Foluke</span>
                </div>
            </div>


        </div>
        <div class="container">
        <form style="position: relative;bottom: 0;" class="form row justify-content-center">
            <div>
                <input type="text" class="input"/>
                 <button type="submit" class="send">send</button>
            </div>
            
        </form>
        </div>
    


    </div>
</section>
    
        





    <script>
        $(document).ready(function () {


            const formEl= document.querySelector(".form");
            const chatmessages =  document.querySelector(".chatsbox");

            formEl.addEventListener("submit",(e)=>{
                e.preventDefault();
                const inputEl = document.querySelector(".input")
                const inputvalue = inputEl.value
                // add to the chats
                chatmessages.insertAdjacentHTML("beforeend",`
                <div class="chatbox">
                    <div class="chatmessages">
                        <div class="chat">${inputvalue}</div>
                    </div>
                    <div class="chat__info">
                        <span class="chat__name">You</span>
                        <img src="{% static 'deku.jpg' %}" class="chat__image" />
                    </div>
                </div>
                `)
                var objDiv = document.getElementById("scrollable");
                objDiv.scrollTop = objDiv.scrollHeight;
                

                message=inputvalue

                
                $.ajax(`http://{{domain}}{% url 'apis:get-response' %}?message=${message}`,   // request url
                        {
                            success: function (data) {// success callback function
                                console.log(data)
                                // add to the chats
                                const aichatmessages =  document.querySelector(".chatsbox");
                                aichatmessages.insertAdjacentHTML("beforeend",`
                                <div class="aichatbox">
                                    <div class="aichatmessages">
                                        <div class="aichat">${data.response}</div>
                                    </div>
                                    <div class="aichat__info">
                                        <img src="{% static 'sakura.jpg' %}" class="aichat__image" />
                                        <span class="aichat__name">Dr Foluke</span>
                                    </div>
                                </div>
                                `)
                                var objDiv = document.getElementById("scrollable");
                                objDiv.scrollTop = objDiv.scrollHeight;
                
                            },
                            error: function (err) {
                                console.log(err)
                            }


                        });
            
                        inputEl.value = ""
                    
            })



        });
    </script>
</body>

</html>